apiVersion: v1
kind: Service
metadata:
  name: workshop-llm-agents
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: llm-agents-port
  selector:
    app: workshop-llm-agents
