apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-argo-workflows-workflow-controller
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-workflows # Argo Workflowsがインストールされているnamespace
roleRef:
  kind: ClusterRole
  name: argo-workflow-argo-workflows-workflow-controller
  apiGroup: rbac.authorization.k8s.io
